import { v4 as uuidv4 } from 'uuid';
import type { UserProfile, DigEvent } from '../types';

const AUTH_KEY = 'trail-dig-auth';
const EVENTS_KEY = 'trail-dig-events';
const PROFILES_KEY = 'trail-dig-profiles';
const SEEDED_KEY = 'trail-dig-seeded';

// Matthews, NC  /  Brevard, NC
const MATTHEWS: [number, number] = [35.1168, -80.7237];

const DEMO_USER = {
  id: 'demo-user-1',
  email: 'demo@trailbuilder.com',
  displayName: 'Trail Builder',
  createdAt: new Date('2026-04-09').toISOString(),
};

const demoProfile: UserProfile = {
  userId: DEMO_USER.id,
  displayName: DEMO_USER.displayName,
  bio: 'Dirt worker and trail enthusiast. Building sustainable singletrack one bench cut at a time.',
  avatarUrl: '',
  location: 'Matthews, NC, United States',
  coordinates: MATTHEWS,
  trailCrew: 'Tarheel Trail Blazers',
  trailCrewUrl: 'https://tarheeltrailblazers.com',
  skills: ['Trail Design', 'Bench Cutting', 'Rock Work', 'Erosion Control', 'Crew Leadership'],
  certifications: ['First Aid / CPR', 'Trail Crew Leader', 'Sawyer Level 1'],
  favoriteTrails: [],
  digStats: { totalDigs: 13, totalHours: 104, totalMiles: 0 },
  socialLinks: { instagram: 'https://instagram.com/trailbuilder', strava: 'https://strava.com/athletes/trailbuilder', facebook: '', website: 'https://trailbuilder.com' },
  gearList: ['McLeod', 'Pick Mattock', 'Shovel', 'Pulaski', 'Rock Bar'],
  availability: [],
  customFields: [],
  theme: {
    accentColor: '#2d6a4f',
    headerImage: '',
    coverPosition: 50,
    showStats: true,
    showGear: true,
    showSocial: true,
    layout: 'standard',
  },
};

const now = new Date();
const day = (offset: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + offset);
  return d.toISOString().split('T')[0];
};

const seedEvents: DigEvent[] = [
  {
    id: uuidv4(),
    creatorId: DEMO_USER.id,
    title: 'Church Street Trail Build',
    description: 'Help us build a new section of flow trail at Church Street Park. We will be cutting bench, installing drain dips, and shaping rollers. Beginners welcome!',
    trailName: 'Church Street Park',
    trailSystem: 'Matthews Trail Network',
    coordinates: MATTHEWS,
    locationName: 'Matthews, NC',
    date: day(3),
    startTime: '8:00 AM',
    endTime: '1:00 PM',
    status: 'confirmed',
    difficulty: 'easy',
    maxVolunteers: 25,
    registeredVolunteers: [DEMO_USER.id],
    providedItems: [
      { name: 'McLeods', quantity: 'Plenty', description: '' },
      { name: 'Shovels', quantity: 'Plenty', description: '' },
      { name: 'Water', quantity: 'Plenty', description: '' },
      { name: 'Gloves', quantity: 'Plenty', description: '' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: '' },
      { name: 'Long pants', essential: true, notes: '' },
      { name: 'Sun protection', essential: false, notes: 'Hat and sunscreen' },
      { name: 'Snacks', essential: false, notes: '' },
    ],
    requirements: [],
    parkingNotes: 'Park at the church lot on Church Street. Trailhead is at the back of the lot.',
    weatherNotes: 'Will cancel if heavy rain. Check the FB event page morning of.',
    contactName: 'Trail Builder',
    contactEmail: 'demo@trailbuilder.com',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: DEMO_USER.id,
    title: 'Rock Garden Rehab at Colonel Beatty',
    description: 'The rock garden at Colonel Beatty has gotten overgrown and loose. We need a crew to clear debris, reset key rocks, and re-establish the line.',
    trailName: 'Colonel Beatty Trail',
    trailSystem: 'Matthews Trail Network',
    coordinates: [35.1196, -80.7230],
    locationName: 'Matthews, NC',
    date: day(10),
    startTime: '8:30 AM',
    endTime: '12:30 PM',
    status: 'confirmed',
    difficulty: 'moderate',
    maxVolunteers: 15,
    registeredVolunteers: [],
    providedItems: [
      { name: 'Rock Bars', quantity: 'Few', description: '' },
      { name: 'Pick Mattocks', quantity: 'Few', description: '' },
      { name: 'Gloves', quantity: 'Plenty', description: '' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: 'Steel toe preferred' },
      { name: 'Work gloves', essential: true, notes: '' },
      { name: 'Eye protection', essential: true, notes: '' },
    ],
    requirements: ['Must be 16+', 'Signed waiver required'],
    parkingNotes: 'Park at the Colonel Beatty Park lot on the corner. We will meet at the picnic shelter.',
    weatherNotes: '',
    contactName: 'Trail Builder',
    contactEmail: 'demo@trailbuilder.com',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: DEMO_USER.id,
    title: 'Pisgah Trail Day — Bennett Gap',
    description: 'Annual spring trail day on Bennett Gap. We will be doing tread work, clearing drains, and brushing back vegetation. This is a classic Pisgah trail and needs love every season.',
    trailName: 'Bennett Gap Trail',
    trailSystem: 'Pisgah National Forest',
    coordinates: [35.2803, -82.7704],
    locationName: 'Brevard, NC',
    date: day(17),
    startTime: '7:00 AM',
    endTime: '3:00 PM',
    status: 'planned',
    difficulty: 'challenging',
    maxVolunteers: 20,
    registeredVolunteers: [],
    providedItems: [
      { name: 'McLeods', quantity: 'Plenty', description: '' },
      { name: 'Hazel Hoes', quantity: 'Few', description: '' },
      { name: 'Hand Saws', quantity: 'Few', description: '' },
      { name: 'Water', quantity: 'Plenty', description: '' },
      { name: 'Lunch', quantity: 'Plenty', description: '' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: '' },
      { name: 'Long pants', essential: true, notes: '' },
      { name: 'Rain jacket', essential: false, notes: 'Mountain weather changes fast' },
      { name: 'Snacks', essential: false, notes: '' },
      { name: 'Chainsaw (if certified)', essential: false, notes: 'Let us know ahead' },
    ],
    requirements: ['Must be 18+', 'Signed waiver required'],
    parkingNotes: 'Meet at the Bennett Gap trailhead on FR 5001. High clearance vehicle recommended.',
    weatherNotes: 'Ride or shine — we work in light rain. Thunderstorms will cancel.',
    contactName: 'Trail Builder',
    contactEmail: 'demo@trailbuilder.com',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: DEMO_USER.id,
    title: 'Sycamore Cycles Shop Ride & Dig',
    description: 'Monthly shop ride followed by trail maintenance on the Dupont Forest trails. We ride 10 miles then spend 2 hours doing tread work. All skill levels welcome. Tools provided by Sycamore Cycles.',
    trailName: 'Dupont State Forest — Ridgeline Trail',
    trailSystem: 'Dupont State Forest',
    coordinates: [35.1983, -82.6208],
    locationName: 'Brevard, NC',
    date: day(24),
    startTime: '9:00 AM',
    endTime: '2:00 PM',
    status: 'planned',
    difficulty: 'easy',
    maxVolunteers: 30,
    registeredVolunteers: [DEMO_USER.id],
    providedItems: [
      { name: 'McLeods', quantity: 'Plenty', description: '' },
      { name: 'Shovels', quantity: 'Plenty', description: '' },
      { name: 'Rakes', quantity: 'Few', description: '' },
      { name: 'Water', quantity: 'Plenty', description: '' },
      { name: 'Snacks', quantity: 'Plenty', description: 'Granola bars and fruit' },
    ],
    recommendedItems: [
      { name: 'Mountain bike', essential: false, notes: 'For the ride portion' },
      { name: 'Helmet', essential: true, notes: 'Required for the ride' },
      { name: 'Sturdy boots', essential: true, notes: '' },
      { name: 'Spare tube', essential: false, notes: '' },
    ],
    requirements: [],
    parkingNotes: 'Park at the Sycamore Cycles lot on Broad St. We shuttle from there.',
    weatherNotes: 'Postponed to following week if heavy rain is forecast.',
    contactName: 'Trail Builder',
    contactEmail: 'demo@trailbuilder.com',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: DEMO_USER.id,
    title: 'Past Dig — Four Mile Creek',
    description: 'We completed a new connector trail at Four Mile Creek Park. Great turnout!',
    trailName: 'Four Mile Creek Greenway',
    trailSystem: 'Matthews Trail Network',
    coordinates: [35.1073, -80.7302],
    locationName: 'Matthews, NC',
    date: day(-14),
    startTime: '8:00 AM',
    endTime: '12:00 PM',
    status: 'completed',
    difficulty: 'easy',
    maxVolunteers: 20,
    registeredVolunteers: [DEMO_USER.id],
    providedItems: [
      { name: 'Shovels', quantity: 'Plenty', description: '' },
      { name: 'McLeods', quantity: 'Plenty', description: '' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: '' },
    ],
    requirements: [],
    parkingNotes: 'Four Mile Creek Park lot.',
    weatherNotes: '',
    contactName: 'Trail Builder',
    contactEmail: 'demo@trailbuilder.com',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: 'other-creator-1',
    title: 'Lake Norman Shoreline Cleanup',
    description: 'Trail stewardship and shoreline cleanup along the Lake Norman loop. Removed debris, cleared invasive species, and refreshed trail markers.',
    trailName: 'Lake Norman Loop',
    trailSystem: 'Lake Norman State Park',
    coordinates: [35.5063, -80.9462],
    locationName: 'Troutman, NC',
    date: day(-45),
    startTime: '9:00 AM',
    endTime: '1:00 PM',
    status: 'completed',
    difficulty: 'easy',
    maxVolunteers: 35,
    registeredVolunteers: [DEMO_USER.id],
    providedItems: [
      { name: 'Gloves', quantity: 'Plenty', description: '' },
      { name: 'Trash Bags', quantity: 'Plenty', description: '' },
      { name: 'Water', quantity: 'Plenty', description: '' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: '' },
      { name: 'Long pants', essential: true, notes: '' },
      { name: 'Sun protection', essential: false, notes: '' },
    ],
    requirements: [],
    parkingNotes: 'Main lot at Lake Norman State Park.',
    weatherNotes: '',
    contactName: 'Park Ranger',
    contactEmail: 'ranger@lknstatepark.org',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: DEMO_USER.id,
    title: 'Backcountry Bridge Repair — South Prong',
    description: 'Replaced two failing puncheon bridges on the South Prong Trail. Heavy timber work with a small experienced crew. All bridges passed inspection.',
    trailName: 'South Prong Trail',
    trailSystem: 'Dupont State Forest',
    coordinates: [35.1856, -82.6023],
    locationName: 'Brevard, NC',
    date: day(-60),
    startTime: '7:00 AM',
    endTime: '4:00 PM',
    status: 'completed',
    difficulty: 'expert',
    maxVolunteers: 8,
    registeredVolunteers: [DEMO_USER.id],
    providedItems: [
      { name: 'Timbers', quantity: 'Plenty', description: 'Pressure-treated 6x6s' },
      { name: 'Hardware', quantity: 'Plenty', description: 'Deck screws and brackets' },
      { name: 'Chainsaws', quantity: 'Few', description: '' },
      { name: 'Water', quantity: 'Plenty', description: '' },
      { name: 'Lunch', quantity: 'Plenty', description: 'Sandwiches and drinks' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: 'Steel toe required' },
      { name: 'Chainsaw chaps', essential: true, notes: '' },
      { name: 'Hard hat', essential: true, notes: '' },
      { name: 'Eye protection', essential: true, notes: '' },
    ],
    requirements: ['Must be 18+', 'Chainsaw certification required'],
    parkingNotes: 'Meet at Guion Farm parking area. Hike in 1.5 miles.',
    weatherNotes: 'Bridge work continues in light rain. Heavy rain postpones.',
    contactName: 'Trail Builder',
    contactEmail: 'demo@trailbuilder.com',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 75).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: 'other-creator-2',
    title: 'UMWELD Beginner Trail Crew Training',
    description: 'Hands-on training for new trail crew volunteers. Covered McLeod technique, bench cutting basics, water bar installation, and trail assessment. Certificates awarded.',
    trailName: 'UMWELD Training Area',
    trailSystem: 'US Forest Service',
    coordinates: [35.3024, -82.4512],
    locationName: 'Hendersonville, NC',
    date: day(-90),
    startTime: '8:30 AM',
    endTime: '3:30 PM',
    status: 'completed',
    difficulty: 'easy',
    maxVolunteers: 20,
    registeredVolunteers: [DEMO_USER.id],
    providedItems: [
      { name: 'McLeods', quantity: 'Plenty', description: '' },
      { name: 'Shovels', quantity: 'Plenty', description: '' },
      { name: 'Training Manuals', quantity: 'Plenty', description: '' },
      { name: 'Water', quantity: 'Plenty', description: '' },
      { name: 'Lunch', quantity: 'Plenty', description: 'Provided by UMWELD' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: '' },
      { name: 'Long pants', essential: true, notes: '' },
      { name: 'Notepad', essential: false, notes: '' },
    ],
    requirements: ['No experience required', 'Must be 16+'],
    parkingNotes: 'UMWELD training center parking lot on Old Hwy 64.',
    weatherNotes: 'Indoor classroom portion regardless of weather. Outdoor portion depends on conditions.',
    contactName: 'UMWELD Training Staff',
    contactEmail: 'training@umweld.org',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 100).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 90).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: DEMO_USER.id,
    title: 'New Connector Trail at Cedar Rock',
    description: 'Opened a new 1.2-mile connector trail linking the Cedar Rock loop to the main Ridgeline Trail. Full bench cut, rolling grade dips, and native stone steps.',
    trailName: 'Cedar Rock Connector',
    trailSystem: 'Pisgah National Forest',
    coordinates: [35.2598, -82.7912],
    locationName: 'Brevard, NC',
    date: day(-120),
    startTime: '7:30 AM',
    endTime: '4:00 PM',
    status: 'completed',
    difficulty: 'moderate',
    maxVolunteers: 12,
    registeredVolunteers: [DEMO_USER.id],
    providedItems: [
      { name: 'McLeods', quantity: 'Plenty', description: '' },
      { name: 'Pick Mattocks', quantity: 'Plenty', description: '' },
      { name: 'Rock Bars', quantity: 'Few', description: '' },
      { name: 'Shovels', quantity: 'Plenty', description: '' },
      { name: 'Water', quantity: 'Plenty', description: '' },
      { name: 'Snacks', quantity: 'Plenty', description: '' },
    ],
    recommendedItems: [
      { name: 'Sturdy boots', essential: true, notes: '' },
      { name: 'Long pants', essential: true, notes: '' },
      { name: 'Work gloves', essential: true, notes: '' },
      { name: 'Knee pads', essential: false, notes: 'Lots of low work' },
    ],
    requirements: ['Must be 18+', 'Signed waiver required'],
    parkingNotes: 'Cedar Rock trailhead on FR 475. High clearance recommended for last mile.',
    weatherNotes: 'Trail work proceeds in all but severe weather.',
    contactName: 'Trail Builder',
    contactEmail: 'demo@trailbuilder.com',
    contactPhone: '',
    imageUrl: '',
    createdAt: new Date(Date.now() - 86400000 * 135).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 120).toISOString(),
  },

  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Trail Build \u2014 Sherman Branch Trail",
    description: "Monthly work party on Sherman Branch Trail. All skill levels welcome. Tools and lunch provided.",
    trailName: "Sherman Branch Trail",
    trailSystem: "Sherman Branch MTB",
    coordinates: [35.0962, -80.7081],
    locationName: "Matthews, NC",
    date: "2026-08-18",
    startTime: "7:00 AM",
    endTime: "11:00 AM",
    status: "planned",
    difficulty: "moderate",
    maxVolunteers: 27,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Snacks", quantity: "Few", description: "" },
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Pick Mattocks", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Few", description: "" },
      { name: "Water", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Sherman Branch Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 34).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-1",
    title: "Retaining Wall Build \u2014 Corn Mill Shoals",
    description: "Stewardship day at Corn Mill Shoals. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "Corn Mill Shoals",
    trailSystem: "Dupont State Forest",
    coordinates: [35.2103, -82.6012],
    locationName: "Brevard, NC",
    date: "2026-09-29",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    status: "planned",
    difficulty: "moderate",
    maxVolunteers: 32,
    registeredVolunteers: [],
    providedItems: [
      { name: "Snacks", quantity: "Few", description: "" },
      { name: "Pick Mattocks", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Eye protection", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Corn Mill Shoals trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 44).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-2",
    title: "Trail Assessment \u2014 Cat Gap Loop",
    description: "Join us for a full day of trail work on Cat Gap Loop. We'll be doing tread work, clearing drains, and improving drainage.",
    trailName: "Cat Gap Loop",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.1538, -82.7432],
    locationName: "Brevard, NC",
    date: "2026-07-13",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    status: "confirmed",
    difficulty: "easy",
    maxVolunteers: 29,
    registeredVolunteers: [],
    providedItems: [
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "Snacks", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Cat Gap Loop trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-4",
    title: "Volunteer Day \u2014 Big Rock Trail",
    description: "Monthly work party on Big Rock Trail. All skill levels welcome. Tools and lunch provided.",
    trailName: "Big Rock Trail",
    trailSystem: "Table Rock State Park",
    coordinates: [35.0398, -82.6962],
    locationName: "Pickens, SC",
    date: "2026-06-23",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "confirmed",
    difficulty: "easy",
    maxVolunteers: 31,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "Gloves", quantity: "Few", description: "" },
      { name: "Water", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Big Rock Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 0).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Bridge Repair \u2014 Crowders Mountain",
    description: "Stewardship day at Crowders Mountain. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "Crowders Mountain",
    trailSystem: "Crowders Mountain State Park",
    coordinates: [35.2181, -81.2917],
    locationName: "Kings Mountain, NC",
    date: "2026-09-04",
    startTime: "9:00 AM",
    endTime: "1:00 PM",
    status: "confirmed",
    difficulty: "challenging",
    maxVolunteers: 12,
    registeredVolunteers: [],
    providedItems: [
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Pick Mattocks", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Crowders Mountain trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 0).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-2",
    title: "Post Storm Cleanup \u2014 Foothills Trail",
    description: "Join us for a full day of trail work on Foothills Trail. We'll be doing tread work, clearing drains, and improving drainage.",
    trailName: "Foothills Trail",
    trailSystem: "Sumter National Forest",
    coordinates: [35.0788, -82.7265],
    locationName: "Cleveland, SC",
    date: "2026-08-09",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "planned",
    difficulty: "moderate",
    maxVolunteers: 14,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Shovels", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Foothills Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Crew Lead",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Step Construction \u2014 Kanuga Trail",
    description: "Join us for a full day of trail work on Kanuga Trail. We'll be doing tread work, clearing drains, and improving drainage.",
    trailName: "Kanuga Trail",
    trailSystem: "Dupont State Forest",
    coordinates: [35.1698, -82.6374],
    locationName: "Cedar Mountain, NC",
    date: "2026-09-14",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "completed",
    difficulty: "moderate",
    maxVolunteers: 33,
    registeredVolunteers: [],
    providedItems: [
      { name: "Water", quantity: "Plenty", description: "" },
      { name: "Water", quantity: "Plenty", description: "" },
      { name: "Rakes", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Kanuga Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Crew Lead",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 39).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-4",
    title: "Work Party \u2014 Kings Mountain Trail",
    description: "Monthly work party on Kings Mountain Trail. All skill levels welcome. Tools and lunch provided.",
    trailName: "Kings Mountain Trail",
    trailSystem: "Kings Mountain State Park",
    coordinates: [35.1206, -81.3389],
    locationName: "Kings Mountain, SC",
    date: "2026-08-13",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "planned",
    difficulty: "moderate",
    maxVolunteers: 28,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Shovels", quantity: "Few", description: "" },
      { name: "Pick Mattocks", quantity: "Plenty", description: "" },
      { name: "Snacks", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Kings Mountain Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 57).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-1",
    title: "Step Construction \u2014 Little River Trail",
    description: "Help us maintain Little River Trail \u2014 one of the most popular trails in the region. Brushing, drain clearing, and tread repair.",
    trailName: "Little River Trail",
    trailSystem: "Dupont State Forest",
    coordinates: [35.1784, -82.6078],
    locationName: "Brevard, NC",
    date: "2026-08-30",
    startTime: "7:00 AM",
    endTime: "11:00 AM",
    status: "completed",
    difficulty: "easy",
    maxVolunteers: 27,
    registeredVolunteers: [],
    providedItems: [
      { name: "Rakes", quantity: "Few", description: "" },
      { name: "Snacks", quantity: "Few", description: "" },
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Shovels", quantity: "Few", description: "" },
      { name: "Rakes", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Little River Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Park Ranger",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 51).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "demo-user-1",
    title: "Trail Reroute \u2014 Corn Mill Shoals",
    description: "Help us maintain Corn Mill Shoals \u2014 one of the most popular trails in the region. Brushing, drain clearing, and tread repair.",
    trailName: "Corn Mill Shoals",
    trailSystem: "Dupont State Forest",
    coordinates: [35.2103, -82.6012],
    locationName: "Brevard, NC",
    date: "2026-08-19",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    status: "confirmed",
    difficulty: "easy",
    maxVolunteers: 14,
    registeredVolunteers: [],
    providedItems: [
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "Rakes", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Corn Mill Shoals trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Trail Maintenance \u2014 Foothills Trail",
    description: "Help us maintain Foothills Trail \u2014 one of the most popular trails in the region. Brushing, drain clearing, and tread repair.",
    trailName: "Foothills Trail",
    trailSystem: "Sumter National Forest",
    coordinates: [35.0788, -82.7265],
    locationName: "Cleveland, SC",
    date: "2026-09-09",
    startTime: "7:00 AM",
    endTime: "11:00 AM",
    status: "confirmed",
    difficulty: "easy",
    maxVolunteers: 33,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "Shovels", quantity: "Few", description: "" },
      { name: "Gloves", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Foothills Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "demo-user-1",
    title: "Trail Maintenance \u2014 Fisher Farm Trail",
    description: "Join us for a full day of trail work on Fisher Farm Trail. We'll be doing tread work, clearing drains, and improving drainage.",
    trailName: "Fisher Farm Trail",
    trailSystem: "Fisher Farm Park",
    coordinates: [35.4245, -80.8322],
    locationName: "Davidson, NC",
    date: "2026-09-17",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    status: "confirmed",
    difficulty: "expert",
    maxVolunteers: 13,
    registeredVolunteers: [],
    providedItems: [
      { name: "Rakes", quantity: "Few", description: "" },
      { name: "Rakes", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Fisher Farm Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 0).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Rolling Grade Dip Install \u2014 Big Rock Trail",
    description: "Help us maintain Big Rock Trail \u2014 one of the most popular trails in the region. Brushing, drain clearing, and tread repair.",
    trailName: "Big Rock Trail",
    trailSystem: "Table Rock State Park",
    coordinates: [35.0398, -82.6962],
    locationName: "Pickens, SC",
    date: "2026-08-19",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    status: "planned",
    difficulty: "challenging",
    maxVolunteers: 31,
    registeredVolunteers: [],
    providedItems: [
      { name: "Water", quantity: "Few", description: "" },
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Big Rock Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Crew Lead",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Tread Work \u2014 Black Mountain Trail",
    description: "Stewardship day at Black Mountain Trail. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "Black Mountain Trail",
    trailSystem: "Croatian National Forest",
    coordinates: [34.9854, -79.3432],
    locationName: "Hoffman, NC",
    date: "2026-08-11",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "confirmed",
    difficulty: "moderate",
    maxVolunteers: 21,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Plenty", description: "" },
      { name: "Rakes", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Black Mountain Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Crew Lead",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 22).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Post Storm Cleanup \u2014 Battle of Charlotte Loop",
    description: "Stewardship day at Battle of Charlotte Loop. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "Battle of Charlotte Loop",
    trailSystem: "Colonel Beatty Park",
    coordinates: [35.1196, -80.723],
    locationName: "Matthews, NC",
    date: "2026-06-26",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "planned",
    difficulty: "moderate",
    maxVolunteers: 24,
    registeredVolunteers: [],
    providedItems: [
      { name: "McLeods", quantity: "Few", description: "" },
      { name: "Gloves", quantity: "Few", description: "" },
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "Pick Mattocks", quantity: "Few", description: "" },
      { name: "Water", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Eye protection", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Battle of Charlotte Loop trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Park Ranger",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 36).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Tread Work \u2014 Farlow Gap",
    description: "Monthly work party on Farlow Gap. All skill levels welcome. Tools and lunch provided.",
    trailName: "Farlow Gap",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.2439, -82.7856],
    locationName: "Brevard, NC",
    date: "2026-10-01",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    status: "completed",
    difficulty: "challenging",
    maxVolunteers: 15,
    registeredVolunteers: [],
    providedItems: [
      { name: "Rakes", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Few", description: "" },
      { name: "McLeods", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Farlow Gap trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Crew Lead",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "demo-user-1",
    title: "Tread Work \u2014 Kanuga Trail",
    description: "Trail crew day on Kanuga Trail. Focus on bench cutting and grade reversals. Experienced crew leads on site.",
    trailName: "Kanuga Trail",
    trailSystem: "Dupont State Forest",
    coordinates: [35.1698, -82.6374],
    locationName: "Cedar Mountain, NC",
    date: "2026-06-16",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "planned",
    difficulty: "easy",
    maxVolunteers: 19,
    registeredVolunteers: [],
    providedItems: [
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Water", quantity: "Few", description: "" },
      { name: "Pick Mattocks", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "Pick Mattocks", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Kanuga Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 38).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-1",
    title: "Step Construction \u2014 Ridgeline Trail",
    description: "Help us maintain Ridgeline Trail \u2014 one of the most popular trails in the region. Brushing, drain clearing, and tread repair.",
    trailName: "Ridgeline Trail",
    trailSystem: "Dupont State Forest",
    coordinates: [35.1958, -82.6278],
    locationName: "Brevard, NC",
    date: "2026-07-05",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "planned",
    difficulty: "easy",
    maxVolunteers: 22,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Ridgeline Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Post Storm Cleanup \u2014 Hickory Nut Gorge Trail",
    description: "Stewardship day at Hickory Nut Gorge Trail. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "Hickory Nut Gorge Trail",
    trailSystem: "Chimney Rock State Park",
    coordinates: [35.4322, -82.2618],
    locationName: "Lake Lure, NC",
    date: "2026-08-24",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "completed",
    difficulty: "easy",
    maxVolunteers: 30,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Pick Mattocks", quantity: "Plenty", description: "" },
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "Water", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Hickory Nut Gorge Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-4",
    title: "Bridge Repair \u2014 Corn Mill Shoals",
    description: "Trail crew day on Corn Mill Shoals. Focus on bench cutting and grade reversals. Experienced crew leads on site.",
    trailName: "Corn Mill Shoals",
    trailSystem: "Dupont State Forest",
    coordinates: [35.2103, -82.6012],
    locationName: "Brevard, NC",
    date: "2026-06-26",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "planned",
    difficulty: "easy",
    maxVolunteers: 31,
    registeredVolunteers: [],
    providedItems: [
      { name: "Rakes", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Few", description: "" },
      { name: "Gloves", quantity: "Few", description: "" },
      { name: "Pick Mattocks", quantity: "Plenty", description: "" },
      { name: "Pick Mattocks", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Corn Mill Shoals trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-1",
    title: "Trail Assessment \u2014 Clawhammer Trail",
    description: "Stewardship day at Clawhammer Trail. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "Clawhammer Trail",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.2222, -82.6988],
    locationName: "Hendersonville, NC",
    date: "2026-08-09",
    startTime: "9:00 AM",
    endTime: "1:00 PM",
    status: "planned",
    difficulty: "easy",
    maxVolunteers: 13,
    registeredVolunteers: [],
    providedItems: [
      { name: "Water", quantity: "Few", description: "" },
      { name: "Gloves", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Eye protection", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Clawhammer Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Crew Lead",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 53).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "demo-user-1",
    title: "Post Storm Cleanup \u2014 Pinnacle Trail",
    description: "Monthly work party on Pinnacle Trail. All skill levels welcome. Tools and lunch provided.",
    trailName: "Pinnacle Trail",
    trailSystem: "Table Rock State Park",
    coordinates: [35.0481, -82.6902],
    locationName: "Pickens, SC",
    date: "2026-06-24",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "confirmed",
    difficulty: "easy",
    maxVolunteers: 27,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Water", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Few", description: "" },
      { name: "Pick Mattocks", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Pinnacle Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 0).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Bridge Repair \u2014 Trace Ridge",
    description: "Trail crew day on Trace Ridge. Focus on bench cutting and grade reversals. Experienced crew leads on site.",
    trailName: "Trace Ridge",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.2588, -82.7401],
    locationName: "Hendersonville, NC",
    date: "2026-09-10",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "confirmed",
    difficulty: "easy",
    maxVolunteers: 9,
    registeredVolunteers: [],
    providedItems: [
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "Shovels", quantity: "Few", description: "" },
      { name: "McLeods", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Eye protection", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Trace Ridge trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Park Ranger",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 34).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-2",
    title: "Trail Maintenance \u2014 Little River Trail",
    description: "Monthly work party on Little River Trail. All skill levels welcome. Tools and lunch provided.",
    trailName: "Little River Trail",
    trailSystem: "Dupont State Forest",
    coordinates: [35.1784, -82.6078],
    locationName: "Brevard, NC",
    date: "2026-10-04",
    startTime: "7:00 AM",
    endTime: "11:00 AM",
    status: "planned",
    difficulty: "moderate",
    maxVolunteers: 22,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Pick Mattocks", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "Water", quantity: "Few", description: "" },
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Pick Mattocks", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Little River Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Brushing Crew \u2014 Spencer Branch",
    description: "Trail crew day on Spencer Branch. Focus on bench cutting and grade reversals. Experienced crew leads on site.",
    trailName: "Spencer Branch",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.2335, -82.7142],
    locationName: "Brevard, NC",
    date: "2026-09-27",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    status: "planned",
    difficulty: "easy",
    maxVolunteers: 20,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Rakes", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Eye protection", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Spencer Branch trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Volunteer Coordinator",
    contactEmail: "ranger@statepark.org",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "demo-user-1",
    title: "Trail Maintenance \u2014 Kitsuma Trail",
    description: "Stewardship day at Kitsuma Trail. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "Kitsuma Trail",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.5722, -82.3114],
    locationName: "Old Fort, NC",
    date: "2026-09-12",
    startTime: "9:00 AM",
    endTime: "1:00 PM",
    status: "confirmed",
    difficulty: "moderate",
    maxVolunteers: 26,
    registeredVolunteers: ["demo-user-1"],
    providedItems: [
      { name: "Gloves", quantity: "Plenty", description: "" },
      { name: "Snacks", quantity: "Plenty", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Hard hat", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Kitsuma Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Park Ranger",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 17).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "demo-user-1",
    title: "Volunteer Day \u2014 Rocky Broad Trail",
    description: "Trail crew day on Rocky Broad Trail. Focus on bench cutting and grade reversals. Experienced crew leads on site.",
    trailName: "Rocky Broad Trail",
    trailSystem: "Lake Lure",
    coordinates: [35.4382, -82.1948],
    locationName: "Lake Lure, NC",
    date: "2026-09-25",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "planned",
    difficulty: "moderate",
    maxVolunteers: 20,
    registeredVolunteers: [],
    providedItems: [
      { name: "Pick Mattocks", quantity: "Few", description: "" },
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Rakes", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Rocky Broad Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Park Ranger",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 43).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-3",
    title: "Sign Installation \u2014 Spencer Branch",
    description: "Trail crew day on Spencer Branch. Focus on bench cutting and grade reversals. Experienced crew leads on site.",
    trailName: "Spencer Branch",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.2335, -82.7142],
    locationName: "Brevard, NC",
    date: "2026-07-29",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    status: "confirmed",
    difficulty: "expert",
    maxVolunteers: 31,
    registeredVolunteers: [],
    providedItems: [
      { name: "Pick Mattocks", quantity: "Few", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Few", description: "" },
      { name: "Rakes", quantity: "Plenty", description: "" },
      { name: "Rakes", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Work gloves", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Spencer Branch trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "other-creator-4",
    title: "Sign Installation \u2014 East Fork Trail",
    description: "Stewardship day at East Fork Trail. We'll be clearing blowdown, refreshing trail markers, and doing erosion control.",
    trailName: "East Fork Trail",
    trailSystem: "Pisgah National Forest",
    coordinates: [35.1276, -82.8267],
    locationName: "Rosman, NC",
    date: "2026-07-17",
    startTime: "9:00 AM",
    endTime: "1:00 PM",
    status: "completed",
    difficulty: "easy",
    maxVolunteers: 28,
    registeredVolunteers: [],
    providedItems: [
      { name: "Water", quantity: "Plenty", description: "" },
      { name: "Shovels", quantity: "Plenty", description: "" },
      { name: "Rakes", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Eye protection", essential: true, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the East Fork Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: uuidv4(),
    creatorId: "demo-user-1",
    title: "Retaining Wall Build \u2014 Green River Trail",
    description: "Trail crew day on Green River Trail. Focus on bench cutting and grade reversals. Experienced crew leads on site.",
    trailName: "Green River Trail",
    trailSystem: "Green River Gamelands",
    coordinates: [35.2569, -82.0594],
    locationName: "Saluda, NC",
    date: "2026-09-14",
    startTime: "7:00 AM",
    endTime: "11:00 AM",
    status: "confirmed",
    difficulty: "easy",
    maxVolunteers: 24,
    registeredVolunteers: [],
    providedItems: [
      { name: "Snacks", quantity: "Plenty", description: "" },
      { name: "Pick Mattocks", quantity: "Few", description: "" },
      { name: "McLeods", quantity: "Plenty", description: "" },
      { name: "McLeods", quantity: "Plenty", description: "" },
      { name: "Shovels", quantity: "Few", description: "" },
    ],
    recommendedItems: [
      { name: "Sturdy boots", essential: true, notes: "" },
      { name: "Long pants", essential: true, notes: "" },
      { name: "Eye protection", essential: false, notes: "" },
    ],
    requirements: [],
    parkingNotes: "Park at the Green River Trail trailhead parking area.",
    weatherNotes: "Event proceeds in light rain. Cancel if thunderstorms.",
    contactName: "Trail Builder",
    contactEmail: "demo@trailbuilder.com",
    contactPhone: "",
    imageUrl: "",
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },

];

export const ensureSeedData = () => {
  if (localStorage.getItem(SEEDED_KEY)) return;

  // Seed auth user
  localStorage.setItem(AUTH_KEY, JSON.stringify(DEMO_USER));

  // Seed registered users (so login works)
  const users = [{ ...DEMO_USER, password: 'demo1234' }];
  localStorage.setItem('trail-dig-users', JSON.stringify(users));

  // Seed profile
  const profiles: Record<string, UserProfile> = {};
  profiles[DEMO_USER.id] = demoProfile;
  localStorage.setItem(PROFILES_KEY, JSON.stringify(profiles));

  // Seed events
  localStorage.setItem(EVENTS_KEY, JSON.stringify(seedEvents));

  localStorage.setItem(SEEDED_KEY, 'true');
};